# Headers
#
hdr_type = ($config.fmt.module_only ? ixx : hxx)
lib{fmt}: include/$hdr_type{**.h}

# Sources
#
src_type = ($cxx.features.modules ? ixx : cxx)
lib{fmt}: src/$src_type{** -fmt}

# Module
#
src/
{
  mxx{fmt}: file{fmt.cc}
  {{
    sed -e 's/^module;/module;\n#include "config.h"/' $path($<) >$path($>)
  }}

  hxx{config}: ../file{config.h.in}
  {{
    diag conf $< -> $>
    cp $path($<) $path($>)
    if! $config.fmt.module_only
      echo "#define FMT_ATTACH_TO_GLOBAL_MODULE" >+$path($>)
    end
    if! $config.fmt.disable_import_std
      echo "#define FMT_IMPORT_STD" >+$path($>)
    end
  }}
}

lib{fmt}: src/hxx{config} src/mxx{fmt}: include = $cxx.features.modules

# Workaround for MSVC bug: https://developercommunity.visualstudio.com/t/Separate-preprocessing-with-P-fails-wit/10707183
# if($build_fmt_module && $cxx.class == 'msvc')
#   cc.reprocess = true

# Build Options
#
cxx.poptions =+ "-I$src_base/include" "-I$out_base/src" "-I$src_base/src"

{objs bmis}{*}: cxx.poptions += -DFMT_LIB_EXPORT

# if $cxx.features.modules
# {
#   cxx.poptions =+ "-I$src_base/src"
#   if! $config.fmt.module_only
#     cxx.poptions += -DFMT_ATTACH_TO_GLOBAL_MODULE
#   if! $config.fmt.disable_import_std
#     cxx.poptions += -DFMT_IMPORT_STD
# }

# Export Options
#
if! $config.fmt.module_only
  lib{fmt}: cxx.export.poptions = "-I$src_base/include"
libs{fmt}: cxx.export.poptions += -DFMT_SHARED

if ($cxx.class == 'msvc')
{
  cxx.poptions += /utf-8
  lib{fmt}: cxx.export.poptions += /utf-8
}

# Metadata
#
lib{fmt}:
{
  export.metadata = 1 fmt
  fmt.has_header = [bool] (!$config.fmt.module_only)
  fmt.has_module = [bool] $cxx.features.modules
}

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{fmt}: bin.lib.version = @"-$version.project_id"
else
  lib{fmt}: bin.lib.version = @"-$version.major.$version.minor"

# Installation
#
if! $config.fmt.module_only
  lib{fmt}: cxx.pkgconfig.include = include/fmtlib/

include/{hxx ixx}{*}:
{
  install         = include/fmtlib/
  install.subdirs = true
}

src/{hxx mxx ixx}{*}:
{
  install         = include/fmtlib/
  install.subdirs = true
}
