# Headers
#
hdr_type = ($config.fmt.module_only ? ixx : hxx)
lib{fmt}: include/$hdr_type{**.h}

# Sources
#
src_type = ($cxx.features.modules ? ixx : cxx)
lib{fmt}: src/$src_type{** -fmt}

# Module
#
# To successfully generate a Binary Module Interface (BMI) after installation,
# the consumer must compile the module interface unit with the same macro
# configuration used during the library's original build.
# Since these macros are only required by the module itself, they should not be
# exported to the consumer's preprocessor scope via 'cxx.export.poptions'.
# To bridge this gap, we generate a persistent 'config.h' that encapsulates the
# package configuration. We then patch the module interface unit to include this
# header within the Global Module Fragment, ensuring the macros are available
# during BMI generation without leaking into the consumer's translation units.
#
lib{fmt}: src/hxx{config} src/mxx{fmt}: include = $cxx.features.modules

src/
{
  # Place the header include immediately after 'module;' to ensure all
  # relevant macros are available before any other macro preprocessing.
  #
  mxx{fmt}: file{fmt.cc}
  {{
    diag patch $< -> $>
    sed -e 's/^module;/module;\n#include "config.h"/' $path($<) >$path($>)
  }}

  # The config header needs to define all macros that were required
  # to compile the module interface unit during the installation.
  #
  hxx{config}: ../file{config.h.in}
  {{
    diag config $< -> $>
    cp $path($<) $path($>)
    if! $config.fmt.module_only
      echo '#define FMT_ATTACH_TO_GLOBAL_MODULE' >+$path($>)
    end
    if! $config.fmt.disable_import_std
      echo '#define FMT_IMPORT_STD' >+$path($>)
    end
  }}
}

# Build and Export Options
#
cxx.poptions =+ "-I$out_base/src" "-I$src_base/src" "-I$src_base/include"

if! $config.fmt.module_only
  lib{fmt}: cxx.export.poptions = "-I$src_base/include"

{objs bmis}{*}: cxx.poptions += -DFMT_LIB_EXPORT
libs{fmt}: cxx.export.poptions += -DFMT_SHARED

if ($cxx.class == 'msvc')
{
  # UTF-8 must be explicitly enabled for MSVC.
  #
  cxx.poptions += /utf-8
  lib{fmt}: cxx.export.poptions += /utf-8

  # Workaround for MSVC Bug
  # Otherwise, MSVC emits error C7657 (private module fragment cannot
  # be declared before a module declaration) when processing the module.
  # See: https://developercommunity.visualstudio.com/t/Separate-preprocessing-with-P-fails-wit/10707183
  #
  if $cxx.features.modules
    cc.reprocess = true
}

# Metadata
#
lib{fmt}:
{
  export.metadata = 1 fmt
  fmt.has_header = [bool] (!$config.fmt.module_only)
  fmt.has_module = [bool] $cxx.features.modules
}

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{fmt}: bin.lib.version = @"-$version.project_id"
else
  lib{fmt}: bin.lib.version = @"-$version.major.$version.minor"

# Installation
#
if! $config.fmt.module_only
  lib{fmt}: cxx.pkgconfig.include = include/fmtlib/

include/{hxx ixx}{*}:
{
  install         = include/fmtlib/
  install.subdirs = true
}

src/{hxx mxx ixx}{*}:
{
  install         = include/fmtlib/
  install.subdirs = true
}
