import! [metadata, rule_hint=cxx.link] libs = fmt%lib{fmt}

./ : exe{driver} : include = $($libs: fmt.has_header)
./ : exe{driver-modules} : include = $($libs: fmt.has_module)

exe{driver} : cxx{driver} ixx{tests} $libs
exe{driver-modules} : cxx{driver-modules} ixx{tests} $libs
