./: fmt/ manifest legal{LICENSE} doc{*.md} doc/doc{**}

# Don't install tests.
#
./: tests/: install = false

# Install documentation to sub-directory.
#
doc/doc{*}:
{
  install         = doc/doc/
  install.subdirs = true
}
